{{- if .Values.amq.operator }}
{{- if .Values.amq.operator.namespace }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ print .Values.amq.name "-og" }}
spec:
  targetNamespaces:
    - {{ .Values.amq.operator.namespace }}
{{- end }}
{{- end }}